# Generated by Django 4.2 on 2023-05-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_delete_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
